### ISSUE TITLE
Integer overflow in sldns_wire2str_pkt_scan

### ISSUE THREAD

**Issue by JiangHeng12138** [NLnetLabs/unbound#611]
version:  unbound-1.11.0

```
sldns/wire2str.c:385:5: runtime error: signed integer overflow: 2146643294 + 1266702 cannot be represented in type 'int'
    #0 0x5b93a7 in sldns_wire2str_pkt_scan /src/unbound/sldns/wire2str.c:385:5
    #1 0x4b24cb in LLVMFuzzerTestOneInput /src/unbound/fuzz_2.c:43:43
    #2 0x443833 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:599:15
    #3 0x42efa2 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:323:6
    #4 0x434c46 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:856:9
    #5 0x45e152 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #6 0x7f9a34eceb26 in __libc_start_main (/lib64/libc.so.6+0x25b26)
    #7 0x40ae59 in _start (/root/oss-fuzz/build/out/unbound/fuzz_2_fuzzer+0x40ae59)
```

**Comment by wcawijngaards** [comment]
I think that the commit fixes the problem, perhaps. The fix stops a domain name printing routine from printing overly long content. Maybe it does not, that depends on what causes the integer overflow. The fix is good to have any way, thanks!
